services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://18.190.206.56:4010/api/v1
    container_name: ecitizen-web
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://18.190.206.56:4010/api/v1
    restart: unless-stopped
    networks:
      - ecitizen-network

networks:
  ecitizen-network:
    external: true
